# CustomerBatchAnalyzeSys config file

# input video stream path
video_stream_input_path: ../input/videostream/

# video steam output path
video_stream_output_path: ../output/videostream/

# local test file path pre for testing debug
input_local_path: ../localtest/

# in one process fetch while fetch batch num video and jump out loop
inner_batch_num: 4

# mount local path pre 
local_pre_path: /data/jianhaod/

# fetch wait list name
shopname: SQ2128
channel: 3
# config shopname and channel map here, sys only fetch wait list
wait_fetch_list:
  - jianhao_test_fetch_list_1

# database redis/mysql config
redis:
 host: 10.255.131.77
 password: redisPassw0rd
 db: 0

# host: 10.255.131.77
# password: redisPassw0rd
# db: 0

#mysql_config:
#  user: vdo_admin
#  pw: vdoPassw0rd
#  ip: 10.255.131.78
#  port: 13306
#  db_name: vdoappdb

