# CustomerBatchAnalyzeSys config file

# input video stream path
video_stream_input_path: ../input/videostream/

# video steam output path
video_stream_output_path: ../output/videostream/

# shopname
shopname: SQ2128

# channel id or camera id
channel: 3

# local test file path pre for testing debug
input_local_path: ../localtest/

# paral num
paralnum: 4

# database redis/mysql config
redis:
 host: 255.255.255.255
 password: test
 db: 0
 wait_file_list: test_list

# host: 10.255.131.77
# password: redisPassw0rd
# db: 0

#mysql_config:
#  user: vdo_admin
#  pw: vdoPassw0rd
#  ip: 10.255.131.78
#  port: 13306
#  db_name: vdoappdb

